name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
      - name: Restore main.dart after create
        run: |
          cp lib/main.dart /tmp/m.dart
          flutter create. --platforms=android --project-name physio_clinic
          cp /tmp/m.dart lib/main.dart
          cat pubspec.yaml
      - run: flutter pub get
      - run: flutter build apk --release --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: physio-clinic-apk
          path: build/app/outputs/flutter-apk/app-release.apk
